version: '3.4'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: user_417
      POSTGRES_PASSWORD: 5KaAme3BT1dHAOimu9lFF05ceR4Bx9fjHB2mbWtbXQDVIaYt0C3KWOqOIHdRzGS55sJ1RLg5evoMscapQeGJwGLodlUz7yTIICMPqEtQdkbHjTfkQmftrWHuI9M93jUp
      POSTGRES_DB: db_417
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@417.co.kr'
      PGADMIN_DEFAULT_PASSWORD: 'qwe123123'
    ports:
      - 3030:80
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - db

  # agent-server:
  #   build:
  #     context: ./agent-server
  #   ports:
  #     - "5001:5000"
  #   depends_on:
  #     - db

  kali:
    image: senghyuk/kali:3.1
    container_name: 'kali'
    tty: true
    ports:
     - "25900:5900"
     - "25901:5901"
    privileged: true